### ISSUE TITLE
Mods have been "patched"

### ISSUE THREAD

**Issue by ghstthedev** [SkyIsntFound1/ALL-QUEST-MODS-V2#8]
Logged onto Gorilla Tag and the mods aren't installed. I had them on there loaded. Before I logged on I was installing Rising Lava and Gorilla Friends. Please help.

**Comment by SkyIsntFound1** [comment]
only the mods on this github work so gorilla friends and rising lava dont work

**Comment by ghstthedev** [comment]
so was the problem me loading rising lava/gorillafriends or was it just the game? cause i've already restored and tried again

**Comment by SkyIsntFound1** [comment]
you can try this:
Deleting the mods that dont work > Options & Tools > Quick Fix > Uninstall App >Reinstall App through Headset > Patch App > Install mods

**Comment by ghstthedev** [comment]
sorry for the wait, but i got it fixed

i uninstalled, rebooted and reinstalled patched and added mods
